config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  constraints SubdomainConstraint do
    scope module: :stores do
      resources :generic_products, only: [:index, :show], as: :store_products do
        get "reviews", on: :member
      end
      root to: 'generic_products#index', as: 'store_root'
      resource :checkout, only: [:show, :create], as: :store_checkout do
        get :new_coffee, on: :collection
      end

      resources :user_purchases, only: [] do
        resources :reviews, only: [:create, :edit, :update], as: :store_review
      end
    end
  end

  resources :generic_products do
    get "my_products", to: "generic_products#user_products", on: :collection
    get "discover", to: "generic_products#index", on: :collection
    get "reviews", on: :member

    resources :attachments, only: [:index, :create, :destroy]
  end

  resources :user_purchases, only: [:index, :create, :show] do
    get "checkout_complete", on: :collection

    resources :reviews, only: [:create, :edit, :update]
  end

  resource :account, only: [:show, :create]
  resource :store, only: [:show, :update]
  resource :coffee, only: [:show, :update], path: "/coffee_widget"

  devise_scope :user do
    get "my_profile" => "devise/registrations#edit", as: :my_profile
  end

  post '/webhooks/:source', to: 'webhooks#create'

  root "generic_products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  has_one :financial, class_name: "ProductFinancial"
  has_one_attached :image
  has_many :user_purchases
  has_many :attachments
  has_many :reviews, through: :user_purchases

  validates :name, :price, :description, presence: true
  validates :price, numericality: { greater_than: 0 }

  scope :with_name, ->(name) { where("name ilike ?", "%#{name}%") if name.present? }
  scope :active, -> { where(active: true) }
end

app/models/store.rb
class Store < ApplicationRecord
  include Rails.application.routes.url_helpers
  DEFAULT_BACKGROUND_COLOR = "#f3f4f6"
  DEFAULT_HIGHTLIGHT_COLOR = "#d4d4d4"

  belongs_to :user
  has_many :generic_products, through: :user
  has_one :coffee_product, through: :user

  delegate :coffee_widget_enabled?, to: :user

  def self.find_by_request(request)
    request.subdomain.present? && find_by(subdomain: request.subdomain)
  end

  def store_url
    return nil unless subdomain.present?

    options = { subdomain: subdomain }
    options.merge!(default_url_options)

    store_root_url(options)
  end

  private

  def default_url_options
    if Rails.env.development? || Rails.env.test?
      { host: 'lvh.me', port: 3000 }
    else
      { host: ENV['HOST'] }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update ]

  def index
    @products = Product
                  .includes(:user, :reviews, image_attachment: :blob)
                  .active
                  .with_name(params[:query])
  end

  def show
    @rating_decorator = RatingDecorator.decorate(@product)
  end

  def new
    @product = Product.new
  end

  def edit
    render
  end

  def create
    @product = Product.new(product_params.merge(user: current_user))

    respond_to do |format|
      if @product.save
        create_stripe_product

        format.html { redirect_to edit_product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to edit_product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_products
    @products = current_user
                  .products
                  .includes(:financial)
                  .with_name(params[:query])
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :user_id, :image, :active)
    end

    def create_stripe_product
      StripeProductJob.perform_later(@product)
    end
end

app/controllers/stores/base_controller.rb
module Stores
  class BaseController < ApplicationController
    layout 'stores'

    skip_before_action :authenticate_user!
    before_action :set_current_store

    def set_current_store
      @store ||= Store.find_by_request(request)
    end
  end
end

app/controllers/stores/checkouts_controller.rb
module Stores
  class CheckoutsController < BaseController

    def new_coffee
      render turbo_stream: turbo_stream_update("modal", "new_coffee", coffee_modal_data)
    end

    def show
      @retries ||= 0

      execute_show
    rescue NoMethodError
      @retries += 1
      sleep 5
      retry if @retries < 10

      raise
    end

    def create
      product = Product.find_by_id(create_params[:generic_product_id])
      service = build_checkout_service(product)
      checkout_session = service.create_session

      redirect_to checkout_session.url, allow_other_host: true, status: :see_other
    end

    private

    def execute_show
      @user_purchase, @coffee_purchase = find_purchases_by_session_id
      @receipt_url = (@user_purchase || @coffee_purchase).receipt_url

      if @user_purchase.present?
        @product = @user_purchase.product
        @attachment_decorator = AttachmentDecorator.decorate(@product)
      end
    end

    def coffee_modal_data
      {
        coffee_product: @store.coffee_product,
        user_purchases: @store
                          .coffee_product
                          .user_purchases
                          .includes(:user, :review)
      }
    end

    def find_purchases_by_session_id
      UserPurchase.uncached do
        generic_purchase = UserPurchase
                            .generic
                            .includes(product: [:user, attachments: [file_attachment: :blob]])
                            .find_by_checkout_session_id(params[:session_id])
        coffee_purchase = UserPurchase
                            .coffee
                            .find_by_checkout_session_id(params[:session_id])

        [ generic_purchase, coffee_purchase ]
      end
    end

    def build_checkout_service(product)
      StripeCheckout.new(
        author: @store.user,
        product: product,
        coffee_params: create_params[:coffee_attributes] || {},
        success_url: store_checkout_url + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url: product.present? ? store_product_url(product) : store_root_url
      )
    end

    def create_params
      params.permit(:generic_product_id, coffee_attributes: [:quantity, :contributor_name, :comment])
    end
  end
end

app/controllers/stores/generic_products_controller.rb
module Stores
  class GenericProductsController < BaseController
    before_action :set_product, only: [:show, :reviews]

    def index
      @products = @store
                    .generic_products
                    .includes(:user, :reviews, image_attachment: :blob)
                    .active
    end

    def show
      @rating_decorator = RatingDecorator.decorate(@product)
    end

    def reviews
      reviews_decorator = ProductReviewsDecorator.decorate(@product)

      render turbo_stream: turbo_stream_update("modal", "generic_products/reviews",
        {
          product: @product,
          reviews: reviews_decorator.reviews
        }
      )
    end

    private

    def set_product
      @product = @store
                  .generic_products
                  .find(params[:id])
    end
  end
end

app/controllers/stores/products_controller.rb
module Stores
  class ProductsController < BaseController
    def index
      @products = @store.products
                        .includes(:user, :reviews, image_attachment: :blob)
                        .active
    end

    def show
      @product = @store.products.find(params[:id])
      @rating_decorator = RatingDecorator.decorate(@product)
    end
  end
end

app/controllers/stores/reviews_controller.rb
module Stores
  class ReviewsController < BaseController
    include ReviewConcern
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store

  def show
    render
  end

  def update
    if @store.update(store_params)
      sync_to_stripe

      redirect_to store_path, notice: "Store details updated."
    else
      flash.now[:error] = error_messages(@store)

      render :show
    end
  end

  private

  def store_params
    params
      .require(:store)
      .permit(:subdomain, :background_color, :highlight_color)
  end

  def sync_to_stripe
    if @store.background_color_previously_changed? || @store.highlight_color_previously_changed?
      StripeAccountJob.perform_later(@store.user.account, action: :update_branding)
    end
  end

  def set_store
    @store = current_user.store ||
             current_user.build_store(background_color: Store::DEFAULT_BACKGROUND_COLOR,
                highlight_color: Store::DEFAULT_HIGHTLIGHT_COLOR)
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def product_show_back_button_path
    product_created_by_current_user? ? my_products_products_path : discover_products_path
  end

  def product_already_purchased?
    current_user.purchases.where(product: @product).any?
  end
end

app/helpers/stores/checkouts_helper.rb
module Stores::CheckoutsHelper
end

app/helpers/stores/generic_products_helper.rb
module Stores::GenericProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/products/index.html.erb
<% content_for :coffee_widget do %>
  <div class="relative">
    <%= link_to new_coffee_store_checkout_url, data: { turbo_method: :get, turbo_prefetch: false }, class: "flex justify-center mt-auto text-lg duration-200 border font-medium focus:outline-none focus:ring-2 inline-flex bg-white hover:bg-gray-300 text-gray-700 border-gray-300 rounded-md shadow-md focus:z-10 py-1 pr-4 pl-2" do %>
      <div class="text-3xl flex items-center justify-center">☕</div>
      <div class="flex items-center justify-center pl-2">Buy me a coffee</div>
    <% end %>
  </div>
<% end %>

<div class="flex flex-wrap -m-4">
  <% @products.each do |product| %>
    <div class="p-4 w-1/3 mt-12">
      <%= render "products/card", product: product, product_page_path: store_product_path(product) %>
    </div>
  <% end %>
</div>

app/views/stores/products/show.html.erb
<div class="w-[850px] mx-auto flex flex-col bg-white shadow p-6 rounded-md border-r-2 border-b-2 border-gray-700">
  <div class="flex px-4 py-4">
    <%= image_tag @product.image, class: "w-[455px] h-[640px] filter saturate-50 rounded-md", alt: @product.name %>

    <div class="flex flex-col w-full px-8 pb-8 pt-8">
      <h1 class="text-4xl text-gray-900 tracking-wide leading-tight font-medium">
        <%= @product.name %>
      </h1>

      <%= link_to @product.user.store.store_url, class: "flex mt-1 text-gray-500 hover:text-gray-700" do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6 mt-0.5 mr-1">
          <path fill-rule="evenodd" d="M18.685 19.097A9.723 9.723 0 0 0 21.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 0 0 3.065 7.097A9.716 9.716 0 0 0 12 21.75a9.716 9.716 0 0 0 6.685-2.653Zm-12.54-1.285A7.486 7.486 0 0 1 12 15a7.486 7.486 0 0 1 5.855 2.812A8.224 8.224 0 0 1 12 20.25a8.224 8.224 0 0 1-5.855-2.438ZM15.75 9a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" clip-rule="evenodd" />
        </svg>

        <span class="text-lg underline font-light"> By <%= @product.user.full_name %> </span>
      <% end %>

      <div class="mt-4">
        <%= render "products/rating" %>
      </div>

      <h1 class="text-4xl text-gray-900 font-semibold mt-10">
        <%= number_to_currency(@product.price) %>
      </h1>

      <%= form_with url: "/checkout", local: true, data: { turbo: false }, class: "flex justify-center mt-auto text-lg duration-200 border font-medium focus:outline-none focus:ring-2 inline-flex bg-white hover:bg-gray-300 text-gray-900 border-gray-900 rounded-md focus:z-10 py-2 pr-4 pl-2" do |form| %>
        <%= form.hidden_field :product_id, value: @product.id %>
        <%= form.button class: "flex justify-center space-x-1" do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
            <path d="M2.25 2.25a.75.75 0 0 0 0 1.5h1.386c.17 0 .318.114.362.278l2.558 9.592a3.752 3.752 0 0 0-2.806 3.63c0 .414.336.75.75.75h15.75a.75.75 0 0 0 0-1.5H5.378A2.25 2.25 0 0 1 7.5 15h11.218a.75.75 0 0 0 .674-.421 60.358 60.358 0 0 0 2.96-7.228.75.75 0 0 0-.525-.965A60.864 60.864 0 0 0 5.68 4.509l-.232-.867A1.875 1.875 0 0 0 3.636 2.25H2.25ZM3.75 20.25a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM16.5 20.25a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0Z" />
          </svg>
          <span>Buy Now</span>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="px-4 py-4 mt-6 border-t border-gray-100">
    <h1 class="text-gray-800 text-3xl leading-none tracking-tight">Product Description:</h1>

    <div class="text-gray-700 mt-4">
      <%= @product.description %>
    </div>
  </div>

  <% if @product.user.store.buy_coffee_widget %>
    <%= render "products/buy_with_coffee", checkout_path: "/checkout", show_tip_giver_input: true %>
  <% end %>
</div>