config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  constraints SubdomainConstraint do
    scope module: :stores do
      resources :generic_products, only: [:index, :show], as: :store_products do
        get "reviews", on: :member
      end
      root to: 'generic_products#index', as: 'store_root'
      resource :checkout, only: [:show, :create], as: :store_checkout do
        get :new_coffee, on: :collection
      end

      resources :user_purchases, only: [] do
        resources :reviews, only: [:create, :edit, :update], as: :store_review
      end
    end
  end

  resources :generic_products do
    get "my_products", to: "generic_products#user_products", on: :collection
    get "discover", to: "generic_products#index", on: :collection
    get "reviews", on: :member

    resources :attachments, only: [:index, :create, :destroy]
  end

  resources :user_purchases, only: [:index, :create, :show] do
    get "checkout_complete", on: :collection

    resources :reviews, only: [:create, :edit, :update]
  end

  resource :account, only: [:show, :create]
  resource :store, only: [:show, :update]
  resource :coffee, only: [:show, :update], path: "/coffee_widget"

  devise_scope :user do
    get "my_profile" => "devise/registrations#edit", as: :my_profile
  end

  post '/webhooks/:source', to: 'webhooks#create'

  root "generic_products#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :product

  has_one_attached :file

  validates :name, :file, presence: true
end

app/models/coffee_product.rb
class CoffeeProduct < Product
  validates :user_id, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  enum :status, { pending: 0, processing: 1, processed: 2, failed: 3 }
end

app/models/generic_product.rb
class GenericProduct < Product
  validates :description, :image, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  has_one :financial, class_name: "ProductFinancial"
  has_one_attached :image
  has_many :user_purchases
  has_many :attachments
  has_many :reviews, through: :user_purchases

  validates :name, :price, :description, presence: true
  validates :price, numericality: { greater_than: 0 }

  scope :with_name, ->(name) { where("name ilike ?", "%#{name}%") if name.present? }
  scope :active, -> { where(active: true) }
end

app/models/product_financial.rb
class ProductFinancial < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/review.rb
class Review < ApplicationRecord
  after_commit :update_product_review_metrics

  belongs_to :user_purchase

  validate :presence_of_rating_or_comment

  private

  def update_product_review_metrics
    ProductReviewJob.perform_later(self)
  end

  def presence_of_rating_or_comment
    if rating.blank? && comment.blank?
      errors.add(:base, "Either rating or comment must be present")
    end
  end
end

app/models/store.rb
class Store < ApplicationRecord
  include Rails.application.routes.url_helpers
  DEFAULT_BACKGROUND_COLOR = "#f3f4f6"
  DEFAULT_HIGHTLIGHT_COLOR = "#d4d4d4"

  belongs_to :user
  has_many :generic_products, through: :user
  has_one :coffee_product, through: :user

  delegate :coffee_widget_enabled?, to: :user

  def self.find_by_request(request)
    request.subdomain.present? && find_by(subdomain: request.subdomain)
  end

  def store_url
    return nil unless subdomain.present?

    options = { subdomain: subdomain }
    options.merge!(default_url_options)

    store_root_url(options)
  end

  private

  def default_url_options
    if Rails.env.development? || Rails.env.test?
      { host: 'lvh.me', port: 3000 }
    else
      { host: ENV['HOST'] }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :generic_products
  has_one :coffee_product
  has_many :user_purchases
  has_many :purchases, -> { generic }, class_name: 'UserPurchase'
  has_many :given_coffees, -> { coffee }, class_name: 'UserPurchase'
  has_many :reviews, through: :purchases
  has_one :account
  has_one :store

  accepts_nested_attributes_for :store

  def full_name
    "#{firstname} #{lastname}".strip.titleize
  end

  def update_name!(name)
    return if name.blank?
    splits = name.split(' ')

    self.update!(firstname: splits.first, lastname: splits.drop(1).join(' '))
  end

  def coffee_widget_enabled?
    coffee_product&.active?
  end
end

app/models/user_purchase.rb
class UserPurchase < ApplicationRecord
  belongs_to :user
  belongs_to :product

  has_one :review

  scope :generic, -> { joins(:product).where(products: {type: 'GenericProduct'}) }
  scope :coffee, -> { joins(:product).where(products: {type: 'CoffeeProduct'}) }
end

app/helpers/application_helper.rb
module ApplicationHelper

  def created_products_tab_color
    current_page?(my_products_generic_products_path) ? "bg-white shadow" : "hover:bg-gray-300"
  end

  def purchases_tab_color
    current_page?(user_purchases_path) ? "bg-white shadow" : "hover:bg-gray-300"
  end

  def account_settings_tab_color
    current_page?(account_path) ? "bg-white shadow" : "hover:bg-gray-300"
  end

  def store_settings_tab_color
    current_page?(store_path) ? "bg-white shadow" : "hover:bg-gray-300"
  end

  def profile_settings_tab_color
    current_page?(my_profile_path) ? "bg-white shadow" : "hover:bg-gray-300"
  end

  def edit_product_tab_color
    current_page?(edit_generic_product_path(@product)) ? "bg-white shadow" : "hover:bg-gray-300"
  end

  def product_attachments_tab_color
    current_page?(generic_product_attachments_path(@product)) ? "bg-white shadow" : "hover:bg-gray-300"
  end

  def coffee_widget_tab_color
    current_page?(coffee_path) ? "bg-white shadow" : "hover:bg-gray-300"
  end

  def coffee_widget_tab_color
    current_page?(coffee_path) ? "bg-white shadow" : "hover:bg-gray-300"
  end

  def product_created_by_current_user?
    @product.user_id == current_user.id
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper

  def devise_action?
    devise_controller? && resource_name == :user && !(controller_name == "registrations" && action_name == "edit")
  end
end

app/helpers/layout_helper.rb
module LayoutHelper

  def layout_by_resource
    devise_action? ? "devise" : "application"
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def product_show_back_button_path
    product_created_by_current_user? ? my_products_products_path : discover_products_path
  end

  def product_already_purchased?
    current_user.purchases.where(product: @product).any?
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/turbo_streams_helper.rb
module TurboStreamsHelper

  def turbo_stream_update(element, partial, locals = {})
    turbo_stream.update(element, partial: partial, locals: locals)
  end
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/shared/_announcement.html.erb
<div class="border border-gray-500 rounded-md p-4 mt-10 flex">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-10 text-gray-700">
    <path d="M16.881 4.345A23.112 23.112 0 0 1 8.25 6H7.5a5.25 5.25 0 0 0-.88 10.427 21.593 21.593 0 0 0 1.378 3.94c.464 1.004 1.674 1.32 2.582.796l.657-.379c.88-.508 1.165-1.593.772-2.468a17.116 17.116 0 0 1-.628-1.607c1.918.258 3.76.75 5.5 1.446A21.727 21.727 0 0 0 18 11.25c0-2.414-.393-4.735-1.119-6.905ZM18.26 3.74a23.22 23.22 0 0 1 1.24 7.51 23.22 23.22 0 0 1-1.41 7.992.75.75 0 1 0 1.409.516 24.555 24.555 0 0 0 1.415-6.43 2.992 2.992 0 0 0 .836-2.078c0-.807-.319-1.54-.836-2.078a24.65 24.65 0 0 0-1.415-6.43.75.75 0 1 0-1.409.516c.059.16.116.321.17.483Z" />
  </svg>

  <span class="text-sm text-gray-500 pl-2">
    <%= message %>
  </span>
</div>

app/views/shared/_edit_product.html.erb
<div class="flex justify-between mb-[52px]">
  <%= link_to product_path(@product), class: "text-gray-500 hover:text-gray-900 flex space-x-1.5" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 9-3 3m0 0 3 3m-3-3h7.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
    </svg>

    <span> Back to listing </span>
  <% end %>
</div>

<div class="flex space-x-1 rounded-lg p-1.5 bg-gray-200 mb-16" data-controller="tab">
  <%= link_to "Product", edit_product_path(@product),
        class: "rounded-md py-2 px-12 text-sm font-medium ring-white ring-opacity-60 ring-offset-2 ring-offset-white focus:outline-none #{edit_product_tab_color}",
        data: { turbo_frame: "tab_content", action: "click->tab#switch", tab_target: "link" } %>
  <%= link_to "Attachments", product_attachments_path(@product),
        class: "rounded-md py-2 px-12 text-sm font-medium ring-white ring-opacity-60 ring-offset-2 ring-offset-white focus:outline-none #{product_attachments_tab_color}",
        data: { turbo_frame: "tab_content", action: "click->tab#switch", tab_target: "link" } %>
</div>

<div>
  <%= turbo_frame_tag "tab_content" do %>
    <%= yield %>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="bg-red-50 border border-red-300 text-red-700 px-4 py-3 rounded relative" role="alert">
    <strong class="font-bold">Oops!</strong>
    <span class="block sm:inline"><%= pluralize(resource.errors.count, "error") %> prohibited this from being saved:</span>
    <ul class="list-disc list-inside">
      <% resource.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_icon.html.erb
<% case flash_type %>
<% when 'notice' %>
  <svg class="flex-shrink-0 size-4 text-blue-500 mt-0.5" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"></path>
  </svg>
<% when 'success' %>
  <svg class="flex-shrink-0 size-4 text-teal-500 mt-0.5" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"></path>
  </svg>
<% when 'error', 'alert' %>
  <svg class="flex-shrink-0 size-4 text-red-500 mt-0.5" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z"></path>
  </svg>
<% when 'warning' %>
  <svg class="flex-shrink-0 size-4 text-yellow-500 mt-0.5" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"></path>
  </svg>
<% end %>

app/views/shared/_library.html.erb
<div class="flex flex-col space-y-4">
  <div class="flex flex-col text-left space-y-1 justify-between">
    <h4 class="text-2xl text-gray-900 font-bold">Hi <%= current_user.firstname %> 👋</h4>
    <p class="text-base text-gray-500 font-medium">Check your Acquired Treasures</p>
  </div>
  <div class="flex space-x-1 rounded-lg p-1.5 bg-gray-200" data-controller="tab">
    <%= link_to "Purchases", user_purchases_path,
          class: "rounded-md py-2 px-12 text-sm font-medium ring-white ring-opacity-60 ring-offset-2 ring-offset-white focus:outline-none #{purchases_tab_color}",
          data: { turbo_frame: "tab_content", action: "click->tab#switch", tab_target: "link" } %>
  </div>
  <div>
    <%= turbo_frame_tag "tab_content" do %>
      <%= yield %>
    <% end %>
  </div>
</div>

app/views/shared/_my_products.html.erb
<div class="flex flex-col space-y-4">
  <div class="flex flex-col text-left space-y-1 justify-between">
    <h4 class="text-2xl text-gray-900 font-bold">Hi <%= current_user.firstname %> 👋</h4>
    <p class="text-base text-gray-500 font-medium">Here's your products history</p>
  </div>
  <div class="flex space-x-1 rounded-lg p-1.5 bg-gray-200" data-controller="tab">
    <%= link_to "Created", my_products_products_path,
          class: "rounded-md py-2 px-12 text-sm font-medium ring-white ring-opacity-60 ring-offset-2 ring-offset-white focus:outline-none #{created_products_tab_color}",
          data: { turbo_frame: "tab_content", action: "click->tab#switch", tab_target: "link" } %>
    <%= link_to "Bought", user_purchases_path,
          class: "rounded-md py-2 px-12 text-sm font-medium ring-white ring-opacity-60 ring-offset-2 ring-offset-white focus:outline-none #{bought_products_tab_color}",
          data: { turbo_frame: "tab_content", action: "click->tab#switch", tab_target: "link" } %>
  </div>
  <div>
    <%= turbo_frame_tag "tab_content" do %>
      <%= yield %>
    <% end %>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<% if user_signed_in? %>
  <div class="flex flex-col w-56 h-screen fixed top-0 left-0 bg-white overflow-y-auto z-30 border-r border-gray-200 shadow-gray-800">
    <div class="flex flex-col pt-5 pb-4 overflow-y-auto">
      <%= link_to root_path, class: "flex items-center flex-shrink-0 text-lg px-8 pb-4 border-b border-gray-200" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-7 mr-1">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 21v-7.5a.75.75 0 0 1 .75-.75h3a.75.75 0 0 1 .75.75V21m-4.5 0H2.36m11.14 0H18m0 0h3.64m-1.39 0V9.349M3.75 21V9.349m0 0a3.001 3.001 0 0 0 3.75-.615A2.993 2.993 0 0 0 9.75 9.75c.896 0 1.7-.393 2.25-1.016a2.993 2.993 0 0 0 2.25 1.016c.896 0 1.7-.393 2.25-1.015a3.001 3.001 0 0 0 3.75.614m-16.5 0a3.004 3.004 0 0 1-.621-4.72l1.189-1.19A1.5 1.5 0 0 1 5.378 3h13.243a1.5 1.5 0 0 1 1.06.44l1.19 1.189a3 3 0 0 1-.621 4.72M6.75 18h3.75a.75.75 0 0 0 .75-.75V13.5a.75.75 0 0 0-.75-.75H6.75a.75.75 0 0 0-.75.75v3.75c0 .414.336.75.75.75Z" />
        </svg>
        <span class="font-semibold">CreatrSouk</span>
      <% end %>
      <div class="mt-5 flex-1 px-2 space-y-1 pb-4 border-b border-gray-200">
        <%= link_to discover_generic_products_path, class: "flex space-x-1.5 items-center px-4 py-2 text-base font-medium rounded-md" +
                ((current_page?(discover_generic_products_path) || current_page?(root_path)) ? " bg-gray-200 text-gray-800" : " hover:bg-gray-200 hover:text-gray-800 text-gray-500") do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22" fill="currentColor" class="w-5 h-4">
            <path fill-rule="evenodd" d="M10.5 3.75a6.75 6.75 0 1 0 0 13.5 6.75 6.75 0 0 0 0-13.5ZM2.25 10.5a8.25 8.25 0 1 1 14.59 5.28l4.69 4.69a.75.75 0 1 1-1.06 1.06l-4.69-4.69A8.25 8.25 0 0 1 2.25 10.5Z" clip-rule="evenodd" />
          </svg>
          <span>Discover</span>
        <% end %>

        <%= link_to user_purchases_path, class: "flex space-x-1.5 items-center px-4 py-2 text-base font-medium rounded-md" +
                (current_page?(user_purchases_path) ? " bg-gray-200 text-gray-800" : " hover:bg-gray-200 hover:text-gray-800 text-gray-500") do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22" fill="currentColor" class="w-5 h-4">
            <path fill-rule="evenodd" d="M1.5 9.832v1.793c0 1.036.84 1.875 1.875 1.875h17.25c1.035 0 1.875-.84 1.875-1.875V9.832a3 3 0 0 0-.722-1.952l-3.285-3.832A3 3 0 0 0 16.215 3h-8.43a3 3 0 0 0-2.278 1.048L2.222 7.88A3 3 0 0 0 1.5 9.832ZM7.785 4.5a1.5 1.5 0 0 0-1.139.524L3.881 8.25h3.165a3 3 0 0 1 2.496 1.336l.164.246a1.5 1.5 0 0 0 1.248.668h2.092a1.5 1.5 0 0 0 1.248-.668l.164-.246a3 3 0 0 1 2.496-1.336h3.165l-2.765-3.226a1.5 1.5 0 0 0-1.139-.524h-8.43Z" clip-rule="evenodd" />
            <path d="M2.813 15c-.725 0-1.313.588-1.313 1.313V18a3 3 0 0 0 3 3h15a3 3 0 0 0 3-3v-1.688c0-.724-.588-1.312-1.313-1.312h-4.233a3 3 0 0 0-2.496 1.336l-.164.246a1.5 1.5 0 0 1-1.248.668h-2.092a1.5 1.5 0 0 1-1.248-.668l-.164-.246A3 3 0 0 0 7.046 15H2.812Z" />
          </svg>
          <span>Library</span>
        <% end %>

        <%= link_to my_products_generic_products_path, class: "flex space-x-1.5 items-center px-4 py-2 text-base font-medium rounded-md" +
                (current_page?(my_products_generic_products_path) ? " bg-gray-200 text-gray-800" : " hover:bg-gray-200 hover:text-gray-800 text-gray-500") do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-4">
            <path d="M21 6.375c0 2.692-4.03 4.875-9 4.875S3 9.067 3 6.375 7.03 1.5 12 1.5s9 2.183 9 4.875Z" />
            <path d="M12 12.75c2.685 0 5.19-.586 7.078-1.609a8.283 8.283 0 0 0 1.897-1.384c.016.121.025.244.025.368C21 12.817 16.97 15 12 15s-9-2.183-9-4.875c0-.124.009-.247.025-.368a8.285 8.285 0 0 0 1.897 1.384C6.809 12.164 9.315 12.75 12 12.75Z" />
            <path d="M12 16.5c2.685 0 5.19-.586 7.078-1.609a8.282 8.282 0 0 0 1.897-1.384c.016.121.025.244.025.368 0 2.692-4.03 4.875-9 4.875s-9-2.183-9-4.875c0-.124.009-.247.025-.368a8.284 8.284 0 0 0 1.897 1.384C6.809 15.914 9.315 16.5 12 16.5Z" />
            <path d="M12 20.25c2.685 0 5.19-.586 7.078-1.609a8.282 8.282 0 0 0 1.897-1.384c.016.121.025.244.025.368 0 2.692-4.03 4.875-9 4.875s-9-2.183-9-4.875c0-.124.009-.247.025-.368a8.284 8.284 0 0 0 1.897 1.384C6.809 19.664 9.315 20.25 12 20.25Z" />
          </svg>

          <span>Store</span>
        <% end %>
      </div>

      <div class="mt-5 flex-1 px-2 space-y-1 pb-4 border-b border-gray-200">
        <%= link_to account_path, class: "flex space-x-1.5 items-center px-4 py-2 text-base font-medium rounded-md" +
                (current_page?(account_path) ? " bg-gray-200 text-gray-800" : " hover:bg-gray-200 hover:text-gray-800 text-gray-500") do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22" fill="currentColor" class="w-5 h-4">
            <path fill-rule="evenodd" d="M11.828 2.25c-.916 0-1.699.663-1.85 1.567l-.091.549a.798.798 0 0 1-.517.608 7.45 7.45 0 0 0-.478.198.798.798 0 0 1-.796-.064l-.453-.324a1.875 1.875 0 0 0-2.416.2l-.243.243a1.875 1.875 0 0 0-.2 2.416l.324.453a.798.798 0 0 1 .064.796 7.448 7.448 0 0 0-.198.478.798.798 0 0 1-.608.517l-.55.092a1.875 1.875 0 0 0-1.566 1.849v.344c0 .916.663 1.699 1.567 1.85l.549.091c.281.047.508.25.608.517.06.162.127.321.198.478a.798.798 0 0 1-.064.796l-.324.453a1.875 1.875 0 0 0 .2 2.416l.243.243c.648.648 1.67.733 2.416.2l.453-.324a.798.798 0 0 1 .796-.064c.157.071.316.137.478.198.267.1.47.327.517.608l.092.55c.15.903.932 1.566 1.849 1.566h.344c.916 0 1.699-.663 1.85-1.567l.091-.549a.798.798 0 0 1 .517-.608 7.52 7.52 0 0 0 .478-.198.798.798 0 0 1 .796.064l.453.324a1.875 1.875 0 0 0 2.416-.2l.243-.243c.648-.648.733-1.67.2-2.416l-.324-.453a.798.798 0 0 1-.064-.796c.071-.157.137-.316.198-.478.1-.267.327-.47.608-.517l.55-.091a1.875 1.875 0 0 0 1.566-1.85v-.344c0-.916-.663-1.699-1.567-1.85l-.549-.091a.798.798 0 0 1-.608-.517 7.507 7.507 0 0 0-.198-.478.798.798 0 0 1 .064-.796l.324-.453a1.875 1.875 0 0 0-.2-2.416l-.243-.243a1.875 1.875 0 0 0-2.416-.2l-.453.324a.798.798 0 0 1-.796.064 7.462 7.462 0 0 0-.478-.198.798.798 0 0 1-.517-.608l-.091-.55a1.875 1.875 0 0 0-1.85-1.566h-.344ZM12 15.75a3.75 3.75 0 1 0 0-7.5 3.75 3.75 0 0 0 0 7.5Z" clip-rule="evenodd" />
          </svg>
          <span>Settings</span>
        <% end %>

        <%= link_to destroy_user_session_path, data: { turbo_method: :delete },
              class: "flex space-x-1.5 items-center px-4 py-2 text-base font-medium rounded-md hover:bg-gray-200 hover:text-gray-800 text-gray-500" do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22" fill="currentColor" class="w-5 h-4">
            <path fill-rule="evenodd" d="M7.5 3.75A1.5 1.5 0 0 0 6 5.25v13.5a1.5 1.5 0 0 0 1.5 1.5h6a1.5 1.5 0 0 0 1.5-1.5V15a.75.75 0 0 1 1.5 0v3.75a3 3 0 0 1-3 3h-6a3 3 0 0 1-3-3V5.25a3 3 0 0 1 3-3h6a3 3 0 0 1 3 3V9A.75.75 0 0 1 15 9V5.25a1.5 1.5 0 0 0-1.5-1.5h-6Zm5.03 4.72a.75.75 0 0 1 0 1.06l-1.72 1.72h10.94a.75.75 0 0 1 0 1.5H10.81l1.72 1.72a.75.75 0 1 1-1.06 1.06l-3-3a.75.75 0 0 1 0-1.06l3-3a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
          </svg>
          <span>Sign Out</span>
        <% end %>
      </div>
    </div>

    <div class="mt-auto flex flex-row space-x-1.5 ps-4 p-4">
      <div class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8 text-gray-500">
          <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
        </svg>
      </div>

      <div class="w-36">
        <div class="text-lg font-semibold text-gray-800 truncate">
          <%= current_user.full_name %>
        </div>
        <div class="text-sm leading-3 text-gray-500 truncate">
          <%= current_user.email %>
        </div>
      </div>
    </div>
  </div>
<% end %>