config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  constraints SubdomainConstraint do
    scope module: :stores do
      resources :generic_products, only: [:index, :show], as: :store_products do
        get "reviews", on: :member
      end
      root to: 'generic_products#index', as: 'store_root'
      resource :checkout, only: [:show, :create], as: :store_checkout do
        get :new_coffee, on: :collection
      end

      resources :user_purchases, only: [] do
        resources :reviews, only: [:create, :edit, :update], as: :store_review
      end
    end
  end

  resources :generic_products do
    get "my_products", to: "generic_products#user_products", on: :collection
    get "discover", to: "generic_products#index", on: :collection
    get "reviews", on: :member

    resources :attachments, only: [:index, :create, :destroy]
  end

  resources :user_purchases, only: [:index, :create, :show] do
    get "checkout_complete", on: :collection

    resources :reviews, only: [:create, :edit, :update]
  end

  resource :account, only: [:show, :create]
  resource :store, only: [:show, :update]
  resource :coffee, only: [:show, :update], path: "/coffee_widget"

  devise_scope :user do
    get "my_profile" => "devise/registrations#edit", as: :my_profile
  end

  post '/webhooks/:source', to: 'webhooks#create'

  root "generic_products#index"
end

app/models/generic_product.rb
class GenericProduct < Product
  validates :description, :image, presence: true
end

app/controllers/generic_products_controller.rb
class GenericProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update reviews ]
  before_action :build_product, only: %i[ new create ]

  def index
    @products = GenericProduct
                  .includes(:user, :reviews, image_attachment: :blob)
                  .active
                  .with_name(params[:query])
  end

  def show
    @rating_decorator = RatingDecorator.decorate(@product)
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @product.assign_attributes(generic_product_params)

    if @product.save
      handle_success("Product was successfully created.")
    else
      handle_failure(:new)
    end
  end

  def update
    if @product.update(generic_product_params)
      handle_success("Product was successfully updated.")
    else
      handle_failure(:edit)
    end
  end

  def user_products
    @products = current_user
                  .generic_products
                  .includes(:financial)
                  .with_name(params[:query])
  end

  def reviews
    reviews_decorator = ProductReviewsDecorator.decorate(@product)

    render turbo_stream: turbo_stream_update("modal", "reviews",
      {
        product: @product,
        reviews: reviews_decorator.reviews
      }
    )
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def build_product
    @product = current_user
                .generic_products
                .new
  end

  def generic_product_params
    params
      .require(:generic_product)
      .permit(:name, :description, :price, :user_id, :image, :active)
  end

  def handle_success(flash_notice)
    sync_to_stripe

    redirect_to edit_generic_product_url(@product), notice: flash_notice
  end

  def handle_failure(render_action)
    render render_action, status: :unprocessable_entity
  end

  def sync_to_stripe
    StripeProductJob.perform_later(
      @product,
      action: determine_stripe_action,
      price_update: @product.price_previously_changed?
    )
  end

  def determine_stripe_action
    @product.id_previously_changed? ? :create : :update
  end
end

app/controllers/stores/generic_products_controller.rb
module Stores
  class GenericProductsController < BaseController
    before_action :set_product, only: [:show, :reviews]

    def index
      @products = @store
                    .generic_products
                    .includes(:user, :reviews, image_attachment: :blob)
                    .active
    end

    def show
      @rating_decorator = RatingDecorator.decorate(@product)
    end

    def reviews
      reviews_decorator = ProductReviewsDecorator.decorate(@product)

      render turbo_stream: turbo_stream_update("modal", "generic_products/reviews",
        {
          product: @product,
          reviews: reviews_decorator.reviews
        }
      )
    end

    private

    def set_product
      @product = @store
                  .generic_products
                  .find(params[:id])
    end
  end
end

app/helpers/generic_products_helper.rb
module GenericProductsHelper

  def product_show_back_button_path
    product_created_by_current_user? ? my_products_generic_products_path : discover_generic_products_path
  end

  def product_already_purchased?
    current_user.purchases.where(product: @product).any?
  end

  def store_url
    store = @product.user.store

    store && store.store_url
  end
end

app/helpers/stores/generic_products_helper.rb
module Stores::GenericProductsHelper
end

app/views/generic_products/_buy_with_coffee.html.erb
<% button_style = store_product ? "background-color: #{@store.highlight_color};" : "" %>

<%= form_with url: checkout_path, local: true, data: { turbo: false } do |form| %>
  <%= form.hidden_field :generic_product_id, value: @product.id %>

  <div class="px-4 py-4 mt-6 border-t border-gray-100">
    <h1 class="text-gray-800 text-3xl leading-none tracking-tight mb-2">Show your support</h1>
    <h1 class="text-gray-400 text-xl leading-none tracking-tight">Buy this product and treat the creator to a Coffee</h1>

    <div class="flex gap-24 mt-10" data-controller="coffee-widget" data-coffee-widget-product-price-value="<%= @product.price %>" data-coffee-widget-coffee-price-value="<%= coffee_product.price %>">
      <div class="basis-1/3 flex flex-col space-y-3 w-fit">
        <div class="flex gap-4 border rounded-xl p-4 hover:ring-gray-500 hover:border-gray-500 border-gray-300">
          <div class="text-5xl flex items-center justify-center">☕</div>
          <div class="flex items-center justify-center text-gray-400 text-xl"> x </div>
          <div class="flex items-center justify-center gap-2">
            <div class="flex items-center justify-center text-gray-700 border-2 w-10 h-10 rounded-full text-xl border-gray-500 bg-gray-300 hover:border-gray-500 hover:bg-gray-300" data-coffee-widget-target="quantityOption" data-action="click->coffee-widget#setAmount" data-coffee-widget-quantity-param="1"> 1 </div>
            <div class="flex items-center justify-center text-gray-700 border-2 w-10 h-10 rounded-full text-xl border-gray-300 hover:border-gray-500 hover:bg-gray-300" data-coffee-widget-target="quantityOption" data-action="click->coffee-widget#setAmount" data-coffee-widget-quantity-param="3"> 3 </div>
            <div class="flex items-center justify-center text-gray-700 border-2 w-10 h-10 rounded-full text-xl border-gray-300 hover:border-gray-500 hover:bg-gray-300" data-coffee-widget-target="quantityOption" data-action="click->coffee-widget#setAmount" data-coffee-widget-quantity-param="5"> 5 </div>
          </div>

          <%= form.number_field "coffee_attributes[quantity]", value: 1, placeholder: "10", min: 1, max: 5000, class: "flex items-center justify-center my-2 h-10 rounded-xl text-center border-2 outline-none focus:ring-gray-500 focus:border-gray-500 border-gray-300", data: { coffee_widget_target: "quantityInput", action: "coffee-widget#setAmount" } %>
        </div>

        <% if store_product %>
          <%= form.text_field "coffee_attributes[contributor_name]", placeholder: "Name", class: "h-12 py-2 px-4 rounded-xl border outline-none placeholder-gray-400 focus:ring-gray-500 focus:border-gray-500 border-gray-300" %>
        <% else %>
          <%= form.hidden_field "coffee_attributes[contributor_name]", value: current_user.full_name %>
        <% end %>

        <%= form.text_area "coffee_attributes[comment]", placeholder: "Say something Nice.", class: "py-2 px-4 rounded-xl border outline-none placeholder-gray-400 focus:ring-gray-500 focus:border-gray-500 border-gray-300", rows: 6 %>
      </div>

      <div class="basis-2/3 flex flex-col justify-between ">
        <div class="flex flex-col space-y-2 text-gray-600 leading-none tracking-tight">
          <h1 class="text-sm text-gray-400 font-semibold mb-2">Total Cost Summary</h1>

          <div class="flex justify-between py-2 border-dotted border-t-2 text-lg border-gray-600">
            <div class="w-2/3 line-clamp-2">
              <%= @product.name %>
            </div>

            <div>
              <%= number_to_currency(@product.price) %>
            </div>
          </div>

          <div class="flex justify-between py-2 text-lg">
            <div class="w-2/3 line-clamp-2">
              Coffee for <%= @product.user.full_name %>
            </div>

            <div data-coffee-widget-target="coffeeAmount">
              <%= number_to_currency(coffee_product.price) %>
            </div>
          </div>

          <div class="flex justify-between py-2 border-dotted border-t-2 text-lg font-bold border-gray-600">
            <div class="">
              Total
            </div>

            <div data-coffee-widget-target="totalAmount">
              <%= number_to_currency(@product.price + 1) %>
            </div>
          </div>
        </div>

        <%= form.button class: "flex justify-center space-x-1 mt-auto text-lg duration-200 border font-medium focus:outline-none focus:ring-2 inline-flex bg-white hover:bg-gray-300 text-gray-900 border-gray-900 rounded-md focus:z-10 py-2 pr-4 pl-2", style: button_style do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
            <path d="M2.25 2.25a.75.75 0 0 0 0 1.5h1.386c.17 0 .318.114.362.278l2.558 9.592a3.752 3.752 0 0 0-2.806 3.63c0 .414.336.75.75.75h15.75a.75.75 0 0 0 0-1.5H5.378A2.25 2.25 0 0 1 7.5 15h11.218a.75.75 0 0 0 .674-.421 60.358 60.358 0 0 0 2.96-7.228.75.75 0 0 0-.525-.965A60.864 60.864 0 0 0 5.68 4.509l-.232-.867A1.875 1.875 0 0 0 3.636 2.25H2.25ZM3.75 20.25a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM16.5 20.25a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0Z" />
          </svg>
          <span>Buy with Coffee</span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/generic_products/_card.html.erb
<%= link_to product_page_path, data: { turbo_frame: "_top" } do %>
  <div class="h-[416px] transform transition duration-500 ease-in-out bg-white rounded-lg shadow hover:shadow-md hover:scale-105 hover:border-gray-300">
    <%= image_tag product.image, class: "h-60 w-full rounded-t-lg object-cover object-center filter saturate-50", alt: product.name %>

    <div class="h-44 p-4 flex flex-col justify-between">
      <div class="flex flex-col">
        <h1 class="mb-1 text-xl font-semibold tracking-tight text-gray-800"><%= product.name %></h1>
        <p class="mb-3 text-sm font-normal text-gray-500 line-clamp-2"><%= product.description %></p>
      </div>

      <div class="flex flex-col space-y-3">
        <div class="flex">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 -2 24 24" stroke-width="1.5" stroke="currentColor" class="size-4 fill-gray-700">
            <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 0 1 1.04 0l2.125 5.111a.563.563 0 0 0 .475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 0 0-.182.557l1.285 5.385a.562.562 0 0 1-.84.61l-4.725-2.885a.562.562 0 0 0-.586 0L6.982 20.54a.562.562 0 0 1-.84-.61l1.285-5.386a.562.562 0 0 0-.182-.557l-4.204-3.602a.562.562 0 0 1 .321-.988l5.518-.442a.563.563 0 0 0 .475-.345L11.48 3.5Z" />
          </svg>

          <div class="text-sm ml-1">
            <% if product.average_rating > 0 %>
              <%= product.average_rating %> (<%= product.reviews_count %>)
            <% else %>
              No ratings
            <% end %>
          </div>
        </div>

        <div class="mt-auto flex justify-between text-gray-800">
          <div class="flex space-x-1.5">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
              <path fill-rule="evenodd" d="M18.685 19.097A9.723 9.723 0 0 0 21.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 0 0 3.065 7.097A9.716 9.716 0 0 0 12 21.75a9.716 9.716 0 0 0 6.685-2.653Zm-12.54-1.285A7.486 7.486 0 0 1 12 15a7.486 7.486 0 0 1 5.855 2.812A8.224 8.224 0 0 1 12 20.25a8.224 8.224 0 0 1-5.855-2.438ZM15.75 9a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" clip-rule="evenodd" />
            </svg>

            <h1 class="text-base underline"><%= product.user.full_name %></h1>
          </div>

          <% unless current_page?(user_purchases_path) %>
            <div class="flex items-center justify-between">
              <div>
                <span class="text-lg font-bold text-gray-900"><%= number_to_currency(product.price) %></span>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/generic_products/_edit_layout.html.erb
<div class="flex justify-between mb-[52px]">
  <%= link_to generic_product_path(@product), class: "text-gray-500 hover:text-gray-900 flex space-x-1.5" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 9-3 3m0 0 3 3m-3-3h7.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
    </svg>

    <span> Back to listing </span>
  <% end %>
</div>

<div class="flex space-x-1 rounded-lg p-1.5 bg-gray-200 mb-16" data-controller="tab">
  <%= link_to "Product", edit_generic_product_path(@product),
        class: "rounded-md py-2 px-12 text-sm font-medium ring-white ring-opacity-60 ring-offset-2 ring-offset-white focus:outline-none #{edit_product_tab_color}",
        data: { turbo_frame: "tab_content", action: "click->tab#switch", tab_target: "link" } %>
  <%= link_to "Attachments", generic_product_attachments_path(@product),
        class: "rounded-md py-2 px-12 text-sm font-medium ring-white ring-opacity-60 ring-offset-2 ring-offset-white focus:outline-none #{product_attachments_tab_color}",
        data: { turbo_frame: "tab_content", action: "click->tab#switch", tab_target: "link" } %>
</div>

<div>
  <%= turbo_frame_tag "tab_content" do %>
    <%= yield %>
  <% end %>
</div>

app/views/generic_products/edit.html.erb
<%= render layout: "generic_products/edit_layout" do %>
  <div class="transition-all border border-gray-200 rounded-md bg-white p-4">
    <div class="flex flex-col gap-1 w-full mb-4">
      <div class="flex items-center">
        <h1 class="text-lg pb-0.5 leading-6 font-medium text-gray-900 mr-2 flex items-center">Edit Product</h1>
      </div>
    </div>

    <%= render "form", product: @product %>
  </div>
<% end %>

app/views/generic_products/new.html.erb
<div class="flex justify-between mb-20">
  <%= link_to my_products_generic_products_path, class: "text-gray-500 hover:text-gray-900 flex space-x-1.5" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 9-3 3m0 0 3 3m-3-3h7.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
    </svg>

    <span> Back to My Products </span>
  <% end %>
</div>

<div class="transition-all border border-gray-200 rounded-md bg-white p-4">
  <div class="flex flex-col gap-1 w-full mb-4">
    <div class="flex items-center">
      <h1 class="text-lg pb-0.5 leading-6 font-medium text-gray-900 mr-2 flex items-center">New Product</h1>
    </div>
  </div>

  <%= render "form", product: @product %>
</div>

app/views/generic_products/show.html.erb
<div class="flex justify-between mb-20">
  <%= link_to product_show_back_button_path, class: "text-gray-500 hover:text-gray-900 flex space-x-1.5" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 9-3 3m0 0 3 3m-3-3h7.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
    </svg>

    <span> Back </span>
  <% end %>

  <% if product_created_by_current_user? %>
    <%= link_to edit_generic_product_path(@product),
          class: "text-sm duration-200 border font-medium focus:outline-none focus:ring-2 inline-flex bg-gray-800 hover:bg-gray-900 text-white border-gray-600 rounded-md focus:z-10 py-2 pr-4 pl-2" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 -1 27 27" stroke-width="1.5" stroke="currentColor" class="h-5 w-5 mr-2">
        <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
      </svg>

      <span>Edit Product</span>
    <% end %>
  <% end %>
</div>

<div class="w-[850px] mx-auto flex flex-col bg-white shadow-xl p-6 rounded-xl">
  <div class="flex px-4 py-4">
    <%= image_tag @product.image, class: "w-[455px] h-[640px] filter saturate-50 rounded-md", alt: @product.name %>

    <div class="flex flex-col w-full px-8 pb-8 pt-8">
      <h1 class="text-4xl text-gray-900 tracking-wide leading-tight font-medium">
        <%= @product.name %>
      </h1>

      <%= link_to store_url, class: "flex mt-1 text-gray-500 hover:text-gray-700" do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6 mt-0.5 mr-1">
          <path fill-rule="evenodd" d="M18.685 19.097A9.723 9.723 0 0 0 21.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 0 0 3.065 7.097A9.716 9.716 0 0 0 12 21.75a9.716 9.716 0 0 0 6.685-2.653Zm-12.54-1.285A7.486 7.486 0 0 1 12 15a7.486 7.486 0 0 1 5.855 2.812A8.224 8.224 0 0 1 12 20.25a8.224 8.224 0 0 1-5.855-2.438ZM15.75 9a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" clip-rule="evenodd" />
        </svg>

        <span class="text-lg underline font-light"> By <%= @product.user.full_name %> </span>
      <% end %>

      <div class="mt-4">
        <%= render "product_rating", reviews_path: reviews_generic_product_path(@product) %>
      </div>

      <h1 class="text-4xl text-gray-900 font-semibold mt-10">
        <%= number_to_currency(@product.price) %>
      </h1>

      <% if product_already_purchased? %>
        <%= render "shared/announcement", message: "You've already purchased this product." %>
      <% end %>

      <% unless product_created_by_current_user? %>
        <%= form_with url: "/user_purchases", local: true, data: { turbo: false }, class: "flex justify-center mt-auto text-lg duration-200 border font-medium focus:outline-none focus:ring-2 inline-flex bg-white hover:bg-gray-300 text-gray-900 border-gray-900 rounded-md focus:z-10 py-2 pr-4 pl-2" do |form| %>
          <%= form.hidden_field :generic_product_id, value: @product.id %>
          <%= form.button class: "flex justify-center space-x-1" do %>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
              <path d="M2.25 2.25a.75.75 0 0 0 0 1.5h1.386c.17 0 .318.114.362.278l2.558 9.592a3.752 3.752 0 0 0-2.806 3.63c0 .414.336.75.75.75h15.75a.75.75 0 0 0 0-1.5H5.378A2.25 2.25 0 0 1 7.5 15h11.218a.75.75 0 0 0 .674-.421 60.358 60.358 0 0 0 2.96-7.228.75.75 0 0 0-.525-.965A60.864 60.864 0 0 0 5.68 4.509l-.232-.867A1.875 1.875 0 0 0 3.636 2.25H2.25ZM3.75 20.25a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM16.5 20.25a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0Z" />
            </svg>
            <span>Buy Now</span>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="px-4 py-4 mt-6 border-t border-gray-100">
    <h1 class="text-gray-800 text-3xl leading-none tracking-tight">Product Description</h1>

    <div class="text-gray-700 mt-4">
      <%= @product.description %>
    </div>
  </div>

  <% if !product_created_by_current_user? && @product.user.coffee_widget_enabled? %>
    <%= render "buy_with_coffee", checkout_path: "/user_purchases", coffee_product: @product.user.coffee_product, store_product: false %>
  <% end %>
</div>

app/views/generic_products/user_products.html.erb
<%= render layout: "shared/my_store" do %>
  <% if current_user.account.present? && current_user.account.details_submitted? %>
    <div class="flex justify-between mt-12 border-b border-gray-200 pb-8">
      <div>
        <%= form_with(url: my_products_generic_products_url, method: "get", local: true, class: "flex") do %>
          <%= text_field_tag :query, params[:query], placeholder: "Search products...", class: "rounded-l-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-1 px-4 bg-white text-gray-700 placeholder-gray-400 shadow text-base focus:outline-none" %>
          <%= button_tag class: "text-sm bg-gray-800 hover:bg-gray-900 text-white py-2 px-2 rounded-r-lg" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
            </svg>
          <% end %>
        <% end %>
      </div>
      <div>
        <%= link_to new_generic_product_path,
              class: "text-sm duration-200 border font-medium focus:outline-none focus:ring-2 inline-flex bg-gray-800 hover:bg-gray-900 text-white border-gray-600 rounded-md focus:z-10 py-2 pr-4 pl-2",
              data: { turbo_frame: "_top" } do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-5 w-5 mr-2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
          </svg>
          <span>Create Product</span>
        <% end %>
      </div>
    </div>

    <table class="min-w-full leading-normal mt-12 shadow">
      <thead>
        <tr>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-200 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            Name
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-200 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            Sales
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-200 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            Revenue
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-200 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            Price
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-200 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            Status
          </th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
              <%= link_to product.name, generic_product_path(product), class: "text-gray-900 hover:underline hover:underline-offset-3 whitespace-no-wrap", data: { turbo_frame: "_top" } %>
            </td>
            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
              <p class="text-gray-900 whitespace-no-wrap"><%= (product.financial&.sales || 0) %></p>
            </td>
            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
              <p class="text-gray-900 whitespace-no-wrap"><%= number_to_currency(product.financial&.revenue&.to_f || 0) %></p>
            </td>
            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
              <p class="text-gray-900 whitespace-no-wrap"><%= number_to_currency(product.price) %></p>
            </td>
            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
              <% if product.active? %>
                <span class="relative inline-block px-3 py-1 font-semibold leading-tight text-green-900">
                  <span aria-hidden="true" class="absolute inset-0 opacity-50 rounded-full bg-green-200"></span>
                  <span class="relative">Active</span>
                </span>
              <% else %>
                <span class="relative inline-block px-3 py-1 font-semibold leading-tight text-red-900">
                  <span aria-hidden="true" class="absolute inset-0 opacity-50 rounded-full bg-red-200"></span>
                  <span class="relative">Inactive</span>
                </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="mt-12 py-10 pl-4 bg-white shadow rounded-lg">
      <h1 class="max-w-2xl mb-2 text-3xl text-gray-800 font-semibold leading-none tracking-tight">Start creating your products.</h1>
      <h1 class="max-w-2xl mb-2 text-xl text-gray-400 leading-none tracking-tight">Connect with Stripe</h1>

      <div class="mt-6">
        <%= render "accounts/onboarding_button", title: 'Get Started' %>
      </div>
    </div>
  <% end %>
<% end %>