config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  constraints SubdomainConstraint do
    scope module: :stores do
      resources :generic_products, only: [:index, :show], as: :store_products do
        get "reviews", on: :member
      end
      root to: 'generic_products#index', as: 'store_root'
      resource :checkout, only: [:show, :create], as: :store_checkout do
        get :new_coffee, on: :collection
      end

      resources :user_purchases, only: [] do
        resources :reviews, only: [:create, :edit, :update], as: :store_review
      end
    end
  end

  resources :generic_products do
    get "my_products", to: "generic_products#user_products", on: :collection
    get "discover", to: "generic_products#index", on: :collection
    get "reviews", on: :member

    resources :attachments, only: [:index, :create, :destroy]
  end

  resources :user_purchases, only: [:index, :create, :show] do
    get "checkout_complete", on: :collection

    resources :reviews, only: [:create, :edit, :update]
  end

  resource :account, only: [:show, :create]
  resource :store, only: [:show, :update]
  resource :coffee, only: [:show, :update], path: "/coffee_widget"

  devise_scope :user do
    get "my_profile" => "devise/registrations#edit", as: :my_profile
  end

  post '/webhooks/:source', to: 'webhooks#create'

  root "generic_products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  has_one :financial, class_name: "ProductFinancial"
  has_one_attached :image
  has_many :user_purchases
  has_many :attachments
  has_many :reviews, through: :user_purchases

  validates :name, :price, :description, presence: true
  validates :price, numericality: { greater_than: 0 }

  scope :with_name, ->(name) { where("name ilike ?", "%#{name}%") if name.present? }
  scope :active, -> { where(active: true) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update ]

  def index
    @products = Product
                  .includes(:user, :reviews, image_attachment: :blob)
                  .active
                  .with_name(params[:query])
  end

  def show
    @rating_decorator = RatingDecorator.decorate(@product)
  end

  def new
    @product = Product.new
  end

  def edit
    render
  end

  def create
    @product = Product.new(product_params.merge(user: current_user))

    respond_to do |format|
      if @product.save
        create_stripe_product

        format.html { redirect_to edit_product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to edit_product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_products
    @products = current_user
                  .products
                  .includes(:financial)
                  .with_name(params[:query])
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :user_id, :image, :active)
    end

    def create_stripe_product
      StripeProductJob.perform_later(@product)
    end
end

app/controllers/stores/products_controller.rb
module Stores
  class ProductsController < BaseController
    def index
      @products = @store.products
                        .includes(:user, :reviews, image_attachment: :blob)
                        .active
    end

    def show
      @product = @store.products.find(params[:id])
      @rating_decorator = RatingDecorator.decorate(@product)
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def product_show_back_button_path
    product_created_by_current_user? ? my_products_products_path : discover_products_path
  end

  def product_already_purchased?
    current_user.purchases.where(product: @product).any?
  end
end

app/views/products/_buy_with_coffee.html.erb
<%= form_with url: checkout_path, local: true, data: { turbo: false } do |form| %>
  <%= form.hidden_field :product_id, value: @product.id %>

  <div class="px-4 py-4 mt-6 border-t border-gray-100">
    <h1 class="text-gray-800 text-3xl leading-none tracking-tight mb-2">Show your support</h1>
    <h1 class="text-gray-400 text-xl leading-none tracking-tight">Buy this product and treat the creator to a Coffee</h1>

    <div class="flex gap-24 mt-10" data-controller="coffee-widget" data-coffee-widget-product-price-value="<%= @product.price %>">
      <div class="basis-1/3 flex flex-col space-y-3 w-fit">
        <div class="flex gap-4 border rounded-xl p-4 hover:ring-gray-500 hover:border-gray-500 border-gray-300">
          <div class="text-5xl flex items-center justify-center">☕</div>
          <div class="flex items-center justify-center text-gray-400 text-xl"> x </div>
          <div class="flex items-center justify-center gap-2">
            <div class="flex items-center justify-center text-gray-700 border-2 w-10 h-10 rounded-full text-xl border-gray-500 bg-gray-300 hover:border-gray-500 hover:bg-gray-300" data-coffee-widget-target="amountOption" data-action="click->coffee-widget#setAmount" data-coffee-widget-option-param="1"> 1 </div>
            <div class="flex items-center justify-center text-gray-700 border-2 w-10 h-10 rounded-full text-xl border-gray-300 hover:border-gray-500 hover:bg-gray-300" data-coffee-widget-target="amountOption" data-action="click->coffee-widget#setAmount" data-coffee-widget-option-param="3"> 3 </div>
            <div class="flex items-center justify-center text-gray-700 border-2 w-10 h-10 rounded-full text-xl border-gray-300 hover:border-gray-500 hover:bg-gray-300" data-coffee-widget-target="amountOption" data-action="click->coffee-widget#setAmount" data-coffee-widget-option-param="5"> 5 </div>
          </div>

          <%= form.number_field :tip_amount, value: 1, placeholder: "10", min: 1, max: 5000, class: "flex items-center justify-center my-2 h-10 rounded-xl text-center border-2 outline-none focus:ring-gray-500 focus:border-gray-500 border-gray-300", data: { coffee_widget_target: "amountInput", action: "coffee-widget#setAmount" } %>
        </div>

        <% if show_tip_giver_input %>
          <%= form.text_field :tip_giver_name, placeholder: "Name", class: "h-12 py-2 px-4 rounded-xl border outline-none placeholder-gray-400 focus:ring-gray-500 focus:border-gray-500 border-gray-300" %>
        <% else %>
          <%= form.hidden_field :tip_giver_name, value: current_user.full_name %>
        <% end %>

        <%= form.text_area :tip_comment, placeholder: "Say something Nice.", class: "py-2 px-4 rounded-xl border outline-none placeholder-gray-400 focus:ring-gray-500 focus:border-gray-500 border-gray-300", rows: 6 %>
      </div>

      <div class="basis-2/3 flex flex-col justify-between ">
        <div class="flex flex-col space-y-2 text-gray-600 leading-none tracking-tight">
          <h1 class="text-sm text-gray-400 font-semibold mb-2">Total Cost Summary</h1>

          <div class="flex justify-between py-2 border-dotted border-t-2 text-lg border-gray-600">
            <div class="w-2/3 line-clamp-2">
              <%= @product.name %>
            </div>

            <div class="">
              <%= number_to_currency(@product.price) %>
            </div>
          </div>

          <div class="flex justify-between py-2 text-lg">
            <div class="w-2/3 line-clamp-2">
              Coffee for <%= @product.user.full_name %>
            </div>

            <div data-coffee-widget-target="coffeeAmount">
              <%= number_to_currency(1) %>
            </div>
          </div>

          <div class="flex justify-between py-2 border-dotted border-t-2 text-lg font-bold border-gray-600">
            <div class="">
              Total
            </div>

            <div data-coffee-widget-target="totalAmount">
              <%= number_to_currency(@product.price + 1) %>
            </div>
          </div>
        </div>

        <%= form.button class: "flex justify-center space-x-1 mt-auto text-lg duration-200 border font-medium focus:outline-none focus:ring-2 inline-flex bg-white hover:bg-gray-300 text-gray-900 border-gray-900 rounded-md focus:z-10 py-2 pr-4 pl-2" do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
            <path d="M2.25 2.25a.75.75 0 0 0 0 1.5h1.386c.17 0 .318.114.362.278l2.558 9.592a3.752 3.752 0 0 0-2.806 3.63c0 .414.336.75.75.75h15.75a.75.75 0 0 0 0-1.5H5.378A2.25 2.25 0 0 1 7.5 15h11.218a.75.75 0 0 0 .674-.421 60.358 60.358 0 0 0 2.96-7.228.75.75 0 0 0-.525-.965A60.864 60.864 0 0 0 5.68 4.509l-.232-.867A1.875 1.875 0 0 0 3.636 2.25H2.25ZM3.75 20.25a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM16.5 20.25a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0Z" />
          </svg>
          <span>Buy with Coffee</span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/products/_edit_layout.html.erb
<div class="flex justify-between mb-[52px]">
  <%= link_to product_path(@product), class: "text-gray-500 hover:text-gray-900 flex space-x-1.5" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 9-3 3m0 0 3 3m-3-3h7.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
    </svg>

    <span> Back to listing </span>
  <% end %>
</div>

<div class="flex space-x-1 rounded-lg p-1.5 bg-gray-200 mb-16" data-controller="tab">
  <%= link_to "Product", edit_product_path(@product),
        class: "rounded-md py-2 px-12 text-sm font-medium ring-white ring-opacity-60 ring-offset-2 ring-offset-white focus:outline-none #{edit_product_tab_color}",
        data: { turbo_frame: "tab_content", action: "click->tab#switch", tab_target: "link" } %>
  <%= link_to "Attachments", product_attachments_path(@product),
        class: "rounded-md py-2 px-12 text-sm font-medium ring-white ring-opacity-60 ring-offset-2 ring-offset-white focus:outline-none #{product_attachments_tab_color}",
        data: { turbo_frame: "tab_content", action: "click->tab#switch", tab_target: "link" } %>
</div>

<div>
  <%= turbo_frame_tag "tab_content" do %>
    <%= yield %>
  <% end %>
</div>

app/views/products/edit.html.erb
<%= render layout: "products/edit_layout" do %>
  <div class="transition-all border border-gray-200 rounded-md bg-white p-4">
    <div class="flex flex-col gap-1 w-full mb-4">
      <div class="flex items-center">
        <h1 class="text-lg pb-0.5 leading-6 font-medium text-gray-900 mr-2 flex items-center">Edit Product</h1>
      </div>
    </div>

    <%= render "form", product: @product %>
  </div>
<% end %>

app/views/products/index.html.erb
<div class="flex justify-between items-center mb-20">
  <div class="flex flex-col text-left space-y-1 justify-between">
    <h4 class="text-2xl text-gray-900 font-bold">🔍 Discover</h4>
    <p class="text-base text-gray-500 font-medium">Explore a World of Unique Products</p>
  </div>

  <div class="relative">
    <%= form_with method: :get, local: true, class: "flex" do |form| %>
      <%= form.text_field :query, value: params[:query], class: 'rounded-l-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-1 px-4 bg-white text-gray-700 placeholder-gray-400 shadow text-base focus:outline-none', placeholder: 'Search products...' %>
      <%= form.button class: 'text-sm bg-gray-800 hover:bg-gray-900 text-white py-2 px-2 rounded-r-lg' do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
        </svg>
      <% end %>
    <% end %>
  </div>
</div>

<div class="flex flex-wrap -m-4">
  <% @products.each do |product| %>
    <div class="p-4 w-1/4 mt-12">
      <%= render "card", product: product, product_page_path: product_path(product) %>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="flex justify-between mb-20">
  <%= link_to my_products_products_path, class: "text-gray-500 hover:text-gray-900 flex space-x-1.5" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 9-3 3m0 0 3 3m-3-3h7.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
    </svg>

    <span> Back to My Products </span>
  <% end %>
</div>

<div class="transition-all border border-gray-200 rounded-md bg-white p-4">
  <div class="flex flex-col gap-1 w-full mb-4">
    <div class="flex items-center">
      <h1 class="text-lg pb-0.5 leading-6 font-medium text-gray-900 mr-2 flex items-center">New Product</h1>
    </div>
  </div>

  <%= render "form", product: @product %>
</div>

app/views/products/show.html.erb
<div class="flex justify-between mb-20">
  <%= link_to product_show_back_button_path, class: "text-gray-500 hover:text-gray-900 flex space-x-1.5" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 9-3 3m0 0 3 3m-3-3h7.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
    </svg>

    <span> Back </span>
  <% end %>

  <% if product_created_by_current_user? %>
    <%= link_to edit_product_path(@product),
          class: "text-sm duration-200 border font-medium focus:outline-none focus:ring-2 inline-flex bg-gray-800 hover:bg-gray-900 text-white border-gray-600 rounded-md focus:z-10 py-2 pr-4 pl-2" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 -1 27 27" stroke-width="1.5" stroke="currentColor" class="h-5 w-5 mr-2">
        <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
      </svg>

      <span>Edit Product</span>
    <% end %>
  <% end %>
</div>

<div class="w-[850px] mx-auto flex flex-col bg-white shadow-xl p-6 rounded-xl">
  <div class="flex px-4 py-4">
    <%= image_tag @product.image, class: "w-[455px] h-[640px] filter saturate-50 rounded-md", alt: @product.name %>

    <div class="flex flex-col w-full px-8 pb-8 pt-8">
      <h1 class="text-4xl text-gray-900 tracking-wide leading-tight font-medium">
        <%= @product.name %>
      </h1>

      <%= link_to @product.user.store.store_url, class: "flex mt-1 text-gray-500 hover:text-gray-700" do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6 mt-0.5 mr-1">
          <path fill-rule="evenodd" d="M18.685 19.097A9.723 9.723 0 0 0 21.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 0 0 3.065 7.097A9.716 9.716 0 0 0 12 21.75a9.716 9.716 0 0 0 6.685-2.653Zm-12.54-1.285A7.486 7.486 0 0 1 12 15a7.486 7.486 0 0 1 5.855 2.812A8.224 8.224 0 0 1 12 20.25a8.224 8.224 0 0 1-5.855-2.438ZM15.75 9a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" clip-rule="evenodd" />
        </svg>

        <span class="text-lg underline font-light"> By <%= @product.user.full_name %> </span>
      <% end %>

      <div class="mt-4">
        <%= render "rating" %>
      </div>

      <h1 class="text-4xl text-gray-900 font-semibold mt-10">
        <%= number_to_currency(@product.price) %>
      </h1>

      <% if product_already_purchased? %>
        <%= render "shared/announcement", message: "You've already purchased this product." %>
      <% end %>

      <% unless product_created_by_current_user? %>
        <%= form_with url: "/user_purchases", local: true, data: { turbo: false }, class: "flex justify-center mt-auto text-lg duration-200 border font-medium focus:outline-none focus:ring-2 inline-flex bg-white hover:bg-gray-300 text-gray-900 border-gray-900 rounded-md focus:z-10 py-2 pr-4 pl-2" do |form| %>
          <%= form.hidden_field :product_id, value: @product.id %>
          <%= form.button class: "flex justify-center space-x-1" do %>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
              <path d="M2.25 2.25a.75.75 0 0 0 0 1.5h1.386c.17 0 .318.114.362.278l2.558 9.592a3.752 3.752 0 0 0-2.806 3.63c0 .414.336.75.75.75h15.75a.75.75 0 0 0 0-1.5H5.378A2.25 2.25 0 0 1 7.5 15h11.218a.75.75 0 0 0 .674-.421 60.358 60.358 0 0 0 2.96-7.228.75.75 0 0 0-.525-.965A60.864 60.864 0 0 0 5.68 4.509l-.232-.867A1.875 1.875 0 0 0 3.636 2.25H2.25ZM3.75 20.25a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM16.5 20.25a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0Z" />
            </svg>
            <span>Buy Now</span>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="px-4 py-4 mt-6 border-t border-gray-100">
    <h1 class="text-gray-800 text-3xl leading-none tracking-tight">Product Description</h1>

    <div class="text-gray-700 mt-4">
      <%= @product.description %>
    </div>
  </div>

  <% if !product_created_by_current_user? && @product.user.store.buy_coffee_widget %>
    <%= render "buy_with_coffee", checkout_path: "/user_purchases", show_tip_giver_input: false %>
  <% end %>
</div>

app/views/products/user_products.html.erb
<%= render layout: "shared/my_store" do %>
  <% if current_user.account.present? && current_user.account.details_submitted? %>
    <div class="flex justify-between mt-12 border-b border-gray-200 pb-8">
      <div>
        <%= form_with(url: my_products_products_url, method: "get", local: true, class: "flex") do %>
          <%= text_field_tag :query, params[:query], placeholder: "Search products...", class: "rounded-l-lg border-transparent flex-1 appearance-none border border-gray-300 w-full py-1 px-4 bg-white text-gray-700 placeholder-gray-400 shadow text-base focus:outline-none" %>
          <%= button_tag class: "text-sm bg-gray-800 hover:bg-gray-900 text-white py-2 px-2 rounded-r-lg" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
            </svg>
          <% end %>
        <% end %>
      </div>
      <div>
        <%= link_to new_product_path,
              class: "text-sm duration-200 border font-medium focus:outline-none focus:ring-2 inline-flex bg-gray-800 hover:bg-gray-900 text-white border-gray-600 rounded-md focus:z-10 py-2 pr-4 pl-2",
              data: { turbo_frame: "_top" } do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-5 w-5 mr-2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
          </svg>
          <span>Create Product</span>
        <% end %>
      </div>
    </div>

    <table class="min-w-full leading-normal mt-12 shadow">
      <thead>
        <tr>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-200 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            Name
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-200 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            Sales
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-200 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            Revenue
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-200 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            Price
          </th>
          <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-200 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
            Status
          </th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
              <%= link_to product.name, product_path(product), class: "text-gray-900 hover:underline hover:underline-offset-3 whitespace-no-wrap", data: { turbo_frame: "_top" } %>
            </td>
            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
              <p class="text-gray-900 whitespace-no-wrap"><%= number_to_currency(product.financial&.sales || 0) %></p>
            </td>
            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
              <p class="text-gray-900 whitespace-no-wrap"><%= number_to_currency(product.financial&.revenue&.to_f || 0) %></p>
            </td>
            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
              <p class="text-gray-900 whitespace-no-wrap"><%= number_to_currency(product.price) %></p>
            </td>
            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
              <% if product.active? %>
                <span class="relative inline-block px-3 py-1 font-semibold leading-tight text-green-900">
                  <span aria-hidden="true" class="absolute inset-0 opacity-50 rounded-full bg-green-200"></span>
                  <span class="relative">Active</span>
                </span>
              <% else %>
                <span class="relative inline-block px-3 py-1 font-semibold leading-tight text-red-900">
                  <span aria-hidden="true" class="absolute inset-0 opacity-50 rounded-full bg-red-200"></span>
                  <span class="relative">Inactive</span>
                </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="mt-12 py-10 pl-4 bg-white shadow rounded-lg">
      <h1 class="max-w-2xl mb-2 text-3xl text-gray-800 font-semibold leading-none tracking-tight">Start creating your products.</h1>
      <h1 class="max-w-2xl mb-2 text-xl text-gray-400 leading-none tracking-tight">Connect with Stripe</h1>

      <div class="mt-6">
        <%= render "accounts/onboarding_button", title: 'Get Started' %>
      </div>
    </div>
  <% end %>
<% end %>